name: Continuous Integration

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        include:
          - os: windows-latest
            platform: windows

          - os: ubuntu-latest
            platform: linux

          - os: macos-latest
            platform: macos

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      # ==========================================
      # Qt
      # ==========================================

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: "6.8.0"

      # ==========================================
      # OpenSSL
      # ==========================================

      - name: Install Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install -y \
            cmake \
            ninja-build \
            libssl-dev

      # ==========================================
      # Configure
      # ==========================================

      - name: Configure
        run: |
          cmake \
            -S . \
            -B build/${{ matrix.platform }} \
            -DCMAKE_BUILD_TYPE=Release

      # ==========================================
      # Build
      # ==========================================

      - name: Build
        run: |
          cmake \
            --build build/${{ matrix.platform }} \
            --config Release

      # ==========================================
      # Upload Build Folder
      # ==========================================

      - name: Upload Build
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.platform }}
          path: build/${{ matrix.platform }}
